import { StyleMetrics, Palette, GroupBox, GridBox } from "std-widgets.slint";
export component MyIconButton inherits Rectangle {
    in property <image> source;
    callback clicked();

    ta := TouchArea {
        clicked => {
            root.clicked();
        }
    }

    width: 50px;
    height: 50px;

    border-radius: 10px;
    background: ta.pressed ? Palette.control-background.transparentize(0.5) : ta.has-hover ? Palette.control-background.brighter(0.3) : Palette.control-background;
    animate background { duration: 150ms; }

    Image {
        width: root.width - 20px;
        height: root.height - 20px;
        source: root.source;
        colorize: Palette.control-foreground;
    }
}
